apiVersion: v1
kind: ConfigMap
metadata:
  name: scp-config
  namespace: open5gs
data:
  scp.yaml.in: |
    logger:
      file:
        path: /var/log/open5gs/scp.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    scp:
      sbi:
        server:
          - address: ${POD_IP}
            port: 7777
        client:
          nrf:
            - uri: http://nrf-svc.open5gs.svc.cluster.local:7777

  run.sh: |
    #!/bin/sh
    set -eu
    : "${POD_IP:?POD_IP is required}"
    sed "s/\${POD_IP}/${POD_IP}/g" /etc/open5gs/scp.yaml.in > /tmp/scp.yaml
    exec open5gs-scpd -c /tmp/scp.yaml
