apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ue
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ueransim-ue
  template:
    metadata:
      labels:
        app: ueransim-ue
    spec:
      containers:
        - name: ue
          image: ueransim:local
          imagePullPolicy: Never
          command: ["/bin/sh", "/etc/ueransim/run-ue.sh"]
          env:
            - name: UE_COUNT
              value: "128"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: ue-config
              mountPath: /etc/ueransim
            - name: dev-net-tun
              mountPath: /dev/net/tun
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: ue-config
          hostPath:
            path: /home/rayen/ieee_5g_core/ueransim-ue
            type: Directory
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
