apiVersion: v1
kind: ConfigMap
metadata:
  name: bsf-config
  namespace: open5gs
data:
  bsf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/bsf.log
      level: info

    bsf:
      sbi:
        dev: eth0
        advertise_name: bsf-svc.open5gs.svc.cluster.local
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://nrf-svc:7777
      serving:
        - plmn_id:
            mcc: "999"
            mnc: "70"

    db_uri: mongodb://mongodb-svc/open5gs
