apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsf
  template:
    metadata:
      labels:
        app: bsf
    spec:
      initContainers:
        - name: wait-mongodb
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z mongodb-svc 27017; do echo waiting for mongodb; sleep 2; done']
      containers:
        - name: bsf
          image: gradiant/open5gs:latest
          command: ["open5gs-bsfd", "-c", "/etc/open5gs/bsf.yaml"]
          ports:
            - containerPort: 7777
          volumeMounts:
            - name: bsf-config
              mountPath: /etc/open5gs/bsf.yaml
              subPath: bsf.yaml
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      volumes:
        - name: bsf-config
          configMap:
            name: bsf-config
