apiVersion: v1
kind: ConfigMap
metadata:
  name: upf-config
  namespace: open5gs
data:
  upf.yaml.in: |
    logger:
      file:
        path: /var/log/open5gs/upf.log
      level: info

    global:
      max:
        ue: 1024

    upf:
      pfcp:
        server:
          - address: 0.0.0.0
      gtpu:
        server:
          - address: 0.0.0.0
      session:
        - subnet: 10.45.0.1/16
          gateway: 10.45.0.1
        - subnet: 2001:db8:cafe::/48
          gateway: 2001:db8:cafe::1
          
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090
  run.sh: |
    #!/bin/sh
    set -eu
    : "${POD_IP:?POD_IP is required}"
    sed "s/\${POD_IP}/${POD_IP}/g" /etc/open5gs/upf.yaml.in > /tmp/upf.yaml
    exec open5gs-upfd -c /tmp/upf.yaml
