apiVersion: v1
kind: Service
metadata:
  name: smf-svc
  namespace: open5gs
spec:
  selector:
    app: smf
  ports:
    - name: sbi
      port: 7777
      targetPort: 7777
    - name: pfcp
      port: 8805
      targetPort: 8805
      protocol: UDP
    - name: gtpc
      port: 2123
      targetPort: 2123
      protocol: UDP
    - name: gtpu
      port: 2152
      targetPort: 2152
      protocol: UDP
    - name: metrics
      port: 9090
      targetPort: 9090
