apiVersion: v1
kind: Service
metadata:
  name: ueransim-gnb
  namespace: open5gs
spec:
  clusterIP: None
  selector:
    app: ueransim-gnb
  ports:
    - name: rls
      port: 4997
      targetPort: 4997
      protocol: UDP
    - name: gtpu
      port: 2152
      targetPort: 2152
      protocol: UDP
